require:
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'public/temp/**/*'
    - 'spec/helpers/**/*'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'spec/**/*_spec.rb'
Layout/EndOfLine:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/vcr_helper.rb'

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
