default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  database: muffon_api
  username: muffon_api
  password: muffon_api
  host: localhost

test:
  <<: *default
  database: muffon_api_test
  username: muffon_api_test
  password: muffon_api_test
  host: localhost

production:
  <<: *default
  database: muffon_api
  username: muffon_api
  password: <%= ENV['MUFFON_API_DATABASE_PASSWORD'] %>
