default: &default
  adapter: postgresql
  encoding: unicode
  pool: 40
  database: <%= Rails.application.credentials.database[:username] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>

development:
  <<: *default
  host: localhost

test:
  <<: *default
  host: localhost

production:
  <<: *default
