:concurrency: 25
:queues:
  - [default, 1]
  - [recommendations_creator, 1]
  - [recommendations_clearer, 1]
  - [artist_tags_updater, 1]
  - [active_storage_analysis, 1]
  - [active_storage_purge, 1]
