local:
  service: Disk
  root: <%= Rails.root.join('storage') %>
  public: true

cloudflare:
  service: S3
  endpoint: https://<%= Rails.application.credentials.storage.account_id %>.r2.cloudflarestorage.com
  access_key_id: <%= Rails.application.credentials.storage.access_key_id %>
  secret_access_key: <%= Rails.application.credentials.storage.secret_access_key %>
  region: auto
  bucket: <%= Rails.application.credentials.storage.bucket %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>
